
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    working_dir: /var/www/symfony
    volumes:
      - .:/var/www/symfony
    environment:
      SYMFONY_ENV: dev
      DATABASE_URL: "postgresql://symfony_user:symfony_password@db:5432/review_service"
    depends_on:
      - db
    command: >
      sh -c "
      composer install &&
      bin/console doctrine:database:create --if-not-exists &&
      bin/console doctrine:migrations:migrate --no-interaction &&
      bin/console doctrine:migrations:migrate --env=test --no-interaction &&
      bin/console doctrine:fixtures:load --no-interaction &&
      ./vendor/bin/phpunit --configuration phpunit.xml.dist &&
      php -S 0.0.0.0:8000 -t public"
    ports:
      - "8000:8000"

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_DB: review_service
      POSTGRES_USER: symfony_user
      POSTGRES_PASSWORD: symfony_password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./.docker/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db-data:
